### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by vanhauser-thc** [AFLplusplus/unicornafl#18]
I get the following error in our afl++ CI when running `build_unicorn_support.sh`:
```
running install
Traceback (most recent call last):
  File "/prg/dev/unicorn_mode/unicornafl/unicorn/bindings/python/setup.py", line 228, in <module>
    setup(
  File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/distutils/dist.py", line 983, in run_command
    cmd_obj = self.get_command_obj(command)
  File "/usr/lib/python3.10/distutils/dist.py", line 858, in get_command_obj
    cmd_obj = self.command_obj[command] = klass(self)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 59, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance
make: *** [GNUmakefile:639: distrib] Error 1
```

**Comment by wtdcode** [comment]
Weird, will have a look.

**Comment by wtdcode** [comment]
I failed to reproduce this bug on my machine. Could you point me to the failed CI run?

**Comment by vanhauser-thc** [comment]
any CI run, e.g.:
https://github.com/AFLplusplus/AFLplusplus/actions/runs/3807265666/jobs/6476796170

**Comment by vanhauser-thc** [comment]
[build.zip](https://github.com/AFLplusplus/unicornafl/files/10335132/build.zip)
you might not be able to see the log, so I attached it here.

**Comment by domenukk** [comment]
> any CI run, e.g.: https://github.com/AFLplusplus/AFLplusplus/actions/runs/3807265666/jobs/6476796170

Seems like this run has nothing to do with unicorn? The error is in argv_fuzzing:

```bash
#15 137.0 make -C utils/argv_fuzzing
#15 137.0 make[1]: Entering directory '/AFLplusplus/utils/argv_fuzzing'
#15 137.2 afl-clang-fast -fsanitize=address -g -o argv_fuzz_persistent_demo argv_fuzz_persistent_demo.c
#15 137.2 make[1]: afl-clang-fast: No such file or directory
#15 137.2 make[1]: *** [Makefile:58: argv_fuzz_persistent_demo] Error 127
#15 137.2 make[1]: Leaving directory '/AFLplusplus/utils/argv_fuzzing'
#15 137.2 make: *** [GNUmakefile:634: distrib] Error 2
------
Dockerfile:87
--------------------
  86 |     
  87 | >>> RUN sed -i.bak 's/^	-/	/g' GNUmakefile && \
  88 | >>>     make clean && make distrib && \
  89 | >>>     ([ "${TEST_BUILD}" ] || (make install && make clean)) && \
  90 | >>>     mv GNUmakefile.bak GNUmakefile
  91 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c sed -i.bak 's/^\t-/\t/g' GNUmakefile &&     make clean && make distrib &&     ([ \"${TEST_BUILD}\" ] || (make install && make clean)) &&     mv GNUmakefile.bak GNUmakefile" did not complete successfully: exit code: 2
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c sed -i.bak 's/^\t-/\t/g' GNUmakefile &&     make clean && make distrib &&     ([ \"${TEST_BUILD}\" ] || (make install && make clean)) &&     mv GNUmakefile.bak GNUmakefile" did not complete successfully: exit code: 2

```

**Comment by vanhauser-thc** [comment]
ah that is a new failure from a PR we got. look at the original posting I made on top.
pushed a fix for this one.

**Comment by vanhauser-thc** [comment]
I still get the error in the first post when running build_unicorn_mode.sh on my system:
```
[100%] Built target bundling_target
[100%] Linking CXX static library libunicornafl.a
make[3]: Leaving directory '/prg/dev/unicorn_mode/unicornafl/build'
[100%] Built target unicornafl
make[2]: Leaving directory '/prg/dev/unicorn_mode/unicornafl/build'
make[1]: Leaving directory '/prg/dev/unicorn_mode/unicornafl/build'
[+] Build process successful!
[*] Installing Unicorn python bindings...
[*] Info: Installing python unicornafl using --user
/prg/dev/unicorn_mode/unicornafl/unicorn/bindings/python/setup.py:12: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils import log
/usr/lib/python3/dist-packages/_distutils_hack/__init__.py:18: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  warnings.warn(
/usr/lib/python3/dist-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
/usr/lib/python3.10/distutils/dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
/usr/lib/python3.10/distutils/dist.py:274: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
/usr/lib/python3.10/distutils/dist.py:274: UserWarning: Unknown distribution option: 'include_package_data'
  warnings.warn(msg)
running install
Traceback (most recent call last):
  File "/prg/dev/unicorn_mode/unicornafl/unicorn/bindings/python/setup.py", line 228, in <module>
    setup(
  File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/distutils/dist.py", line 983, in run_command
    cmd_obj = self.get_command_obj(command)
  File "/usr/lib/python3.10/distutils/dist.py", line 858, in get_command_obj
    cmd_obj = self.command_obj[command] = klass(self)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 59, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance
```

**Comment by domenukk** [comment]
The error occurs if we call `./setup.py` directly, instead of installing with pip.
I have moved the afl++ scripts to pip in this commit:
https://github.com/AFLplusplus/AFLplusplus/commit/94d1740390acee396f4615a4a2a518f10f6bc02d
and opened a PR to als fix the `./setup.py` installation, however it seems that this is deprecated, anyway. 
https://github.com/unicorn-engine/unicorn/pull/1756
